#thymeleaf模板
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootzs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#日志打印
logging:
  level:
    root: warn
    com.yrp: info
  file: log/-blogpro.log
server:
  port: 80
